PSV<-c("LTV", "Land LTV", "FOIR", "Customer Type", "CIBIL Combined", "FCU Status")
x<-c("Is Property Situated in Approved Area","Contactable","Is Phone Verified","Is Dedupe Check positive","Occupation Type","Household Expenses","Income Fragmentation Income type","Education","Credit Risk","Is Income calculated as per IOM")
p<-combn(x,2,FUN = NULL,simplify = TRUE)
q<-combn(x,3,FUN = NULL,simplify = TRUE)
r<-combn(x,4,FUN=NULL,simplify = TRUE)
s<-combn(x,5,FUN=NULL,simplify=TRUE)
t<-combn(x,6,FUN=NULL,simplify=TRUE)
m<-list(p,q,r,s,t)
sum(ncol(p)+ncol(q)+ncol(r)+ncol(s)+ncol(t))
class(p)
set.seed(134)
PSV1<-matrix(sample(PSV,size = 5,replace = FALSE),nrow = 5)
View(PSV1)
set.seed(123)
sample1<-matrix(sample(p,size = nrow(p),replace = F),nrow=nrow(p))
View(sample1)
sample2<-matrix(sample(q,size = nrow(q),replace = F),nrow=nrow(q))
View(sample2)
sample3<-matrix(sample(r,size = nrow(r),replace = F),nrow=nrow(r))
View(sample3)
sample4<-matrix(sample(s,size = nrow(s),replace = F),nrow=nrow(s))
View(sample4)
sample5<-matrix(sample(t,size = nrow(t),replace=F),nrow=nrow(t))
View(sample5)
V7<-rbind(PSV1,sample1)
V8<-rbind(PSV1,sample2)
V9<-rbind(PSV1,sample3)
V10<-rbind(PSV1,sample4)
V11<-rbind(PSV1,sample5)
