PSV<-c("LTV", "Land LTV", "FOIR", "Customer Type", "CIBIL Combined", "FCU Status")
x<-c("Is Property Situated in Approved Area","Contactable","Is Phone Verified","Is Dedupe Check positive","Occupation Type","Household Expenses","Income Fragmentation Income type","Education","Credit Risk","Is Income calculated as per IOM")
p<-combn(x,2,FUN = NULL,simplify = TRUE)
q<-combn(x,3,FUN = NULL,simplify = TRUE)
r<-combn(x,4,FUN=NULL,simplify = TRUE)
s<-combn(x,5,FUN=NULL,simplify=TRUE)
t<-combn(x,6,FUN=NULL,simplify=TRUE)
m<-list(p,q,r,s,t)
sum(ncol(p)+ncol(q)+ncol(r)+ncol(s)+ncol(t))
class(p)
set.seed(134)
PSV1<-combn(matrix(PSV),5,fun = NULL,simplify = TRUE)
View(PSV1)
V7<-rbind(PSV1,p)
V8<-rbind(PSV1,sample2)
V9<-rbind(PSV1,sample3)
V10<-rbind(PSV1,sample4)
V11<-rbind(PSV1,sample5)
