PSV<-c("Land LTV", "FOIR", "Customer Type", "CIBIL Combined", "FCU Status")
class(PSV)
PSV<-as.matrix(PSV)
View(PSV)
x<-c("Is Property Situated in Approved Area","Contactable","Is Phone Verified","Is Dedupe Check positive","Occupation Type","Household Expenses","Income Fragmentation Income type","Education","Credit Risk","Is Income calculated as per IOM")
p<-combn(x,2,FUN = NULL,simplify = TRUE)
class(p)
View(p)
q<-combn(x,3,FUN = NULL,simplify = TRUE)
r<-combn(x,4,FUN=NULL,simplify = TRUE)
s<-combn(x,5,FUN=NULL,simplify=TRUE)
t<-combn(x,6,FUN=NULL,simplify=TRUE)
m<-list(p,q,r,s,t)
sum(ncol(p)+ncol(q)+ncol(r)+ncol(s)+ncol(t))
class(p)
set.seed(134)
V7<-apply(p,2,function(x)c(PSV,x))
View(V7)
V8<-apply(q,2,function(x)c(PSV,x))
View(V8)
V9<-apply(r,2,function(x)c(PSV,x))
View(V9)
V10<-apply(s,2,function(x)c(PSV,x))
View(V10)
V11<-apply(t,2,function(x)c(PSV,x))
View(V11)
sum(ncol(V7)+ncol(V8)+ncol(V9)+ncol(V10)+ncol(V11))
