library(tm)
docs <- Corpus(DirSource("C:/Users/manis/Desktop/Text Mining/opinion-lexicon-English"))
docs
writeLines(as.character(docs[[1]]))
getTransformations()
toSpace <- content_transformer(function(x, pattern) {return (gsub(pattern, " ", x))})
docs <- tm_map(docs, toSpace, "-")
docs <- tm_map(docs, toSpace, ",")
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, removePunctuation)
writeLines(as.character(docs[[1]]))
docs <- tm_map(docs,content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
writeLines(as.character(docs[[1]]))
docs <- tm_map(docs, stripWhitespace)
writeLines(as.character(docs[[1]]))
dtm <- DocumentTermMatrix(docs)
dtm<-t(dtm)
writeLines(as.character(docs[[1]]))
freq <- colSums(as.matrix(dtm))
length(freq)
ord <- order(freq,decreasing=TRUE)
freq[head(ord)]
findFreqTerms(dtm,lowfreq=2)
wf=data.frame(term=names(freq),occurrences=freq)
library(ggplot2)
p <- ggplot(subset(wf, freq>2), aes(term, occurrences))
p <- p + geom_bar(stat="identity")
p <- p + theme(axis.text.x=element_text(size=8,angle=90, hjust=1))
p

library(wordcloud)
set.seed(42)
wordcloud(names(freq),freq, min.freq=10)
wordcloud(names(freq),freq,min.freq=10,colors=brewer.pal(6,"Dark2"))
##########################################################################
m <- as.matrix(dtm)
d <- dist(m)
View(m)
groups <- hclust(d,method="ward.D")
par(cex=0.1,font=3)
plot(groups, hang=-1)
rect.hclust(groups,2)
library(cluster)
kfit <- kmeans(d, 2, nstart=100)
par(cex=0.1,font=3)
clusplot(m, kfit$cluster, color=T, shade=T, labels=2, lines=0)
